### Site Settings ###
title               : Tergel Myagmarsaikhan
description         : >-
                      Data engineering, reliable pipelines, and applied AI projects by Tergel Myagmarsaikhan.
baseurl             : ""   # Change to empty quotes if you are hosting your site at <your-username>.github.io directly,
#                                             otherwise will be hosted at <your-username>.github.io/{{base_url}}
repository          : tergelm2/tergelm2.github.io
open_new_tab        : true
theme               : null


### Plugins ###
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - mini_magick

### To specify which port to host locally on -- use if you have multiple sites you want to host 
port: 4008

sass:
  sass_dir: _sass

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only
  - pages/blog.html # comment out this line if you want a blog!



### Author Info ###
author:
  name              : Tergel Myagmarsaikhan
  image             : /assets/images/tergel-headshot.png
  email             : tergel.myag@gmail.com
#  behance           : your_username
# dribbble          : your_username
#  facebook          : your_username
  github            : tergelm2
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : tergel-myagmarsaikhan-a437b2327
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
#  twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
## Add yours here if you have other stuff in your github.io page!!!**
exclude:
  - README.md
  - README.md~
  - CONTRIBUTING.md
  - LICENSE.md
  - LICENSE.md~
  - config.yml~
  - "*.log"
  - "*.ipynb"
  - "python_notebooks/*"
  - vendor
